/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw2(PApplet appc, GWinData data) { //_CODE_:window1:583834:
  appc.background(230);
} //_CODE_:window1:583834:

public void moistureLevelChange(GSlider source, GEvent event) { //_CODE_:moistureLevel:810801:
  println("moistureLevel - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:moistureLevel:810801:

public void tempChange(GSlider source, GEvent event) { //_CODE_:temperature:206955:
  println("temperature - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:temperature:206955:

public void slider1_change1(GSlider source, GEvent event) { //_CODE_:slider1:792172:
  println("slider1 - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:slider1:792172:

public void atmoChange(GSlider source, GEvent event) { //_CODE_:atmosphere:814010:
  println("atmosphere - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:atmosphere:814010:

public void populationChange(GSlider source, GEvent event) { //_CODE_:population:801352:
  println("population - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:population:801352:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 410, 210, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw2");
  moistureLevel = new GSlider(window1, 3, 31, 209, 40, 10.0);
  moistureLevel.setLimits(50.0, 0.0, 100.0);
  moistureLevel.setNumberFormat(G4P.DECIMAL, 2);
  moistureLevel.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  moistureLevel.setOpaque(false);
  moistureLevel.addEventHandler(this, "moistureLevelChange");
  label1 = new GLabel(window1, 5, 6, 103, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Moisture Level");
  label1.setOpaque(false);
  label2 = new GLabel(window1, 1, 73, 80, 20);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Temperature");
  label2.setOpaque(false);
  temperature = new GSlider(window1, 3, 93, 210, 40, 10.0);
  temperature.setLimits(10.0, -20.0, 40.0);
  temperature.setNumberFormat(G4P.DECIMAL, 2);
  temperature.setLocalColorScheme(GCScheme.RED_SCHEME);
  temperature.setOpaque(false);
  temperature.addEventHandler(this, "tempChange");
  label3 = new GLabel(window1, 5, 139, 122, 20);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("Chance of Disaster");
  label3.setOpaque(false);
  slider1 = new GSlider(window1, 4, 165, 210, 40, 10.0);
  slider1.setLimits(25.0, 0.0, 50.0);
  slider1.setNumberFormat(G4P.DECIMAL, 2);
  slider1.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  slider1.setOpaque(false);
  slider1.addEventHandler(this, "slider1_change1");
  label4 = new GLabel(window1, 210, 7, 80, 20);
  label4.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label4.setText("Atmospheric Strength");
  label4.setOpaque(false);
  atmosphere = new GSlider(window1, 300, 34, 167, 100, 10.0);
  atmosphere.setRotation(PI/2, GControlMode.CORNER);
  atmosphere.setLimits(1.0, 0.0, 5.0);
  atmosphere.setNumberFormat(G4P.DECIMAL, 2);
  atmosphere.setOpaque(false);
  atmosphere.addEventHandler(this, "atmoChange");
  label5 = new GLabel(window1, 287, 9, 80, 20);
  label5.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label5.setText("Population");
  label5.setOpaque(false);
  population = new GSlider(window1, 363, 38, 167, 100, 10.0);
  population.setRotation(PI/2, GControlMode.CORNER);
  population.setLimits(500.0, 0.0, 10000.0);
  population.setNumberFormat(G4P.DECIMAL, 2);
  population.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  population.setOpaque(false);
  population.addEventHandler(this, "populationChange");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GSlider moistureLevel; 
GLabel label1; 
GLabel label2; 
GSlider temperature; 
GLabel label3; 
GSlider slider1; 
GLabel label4; 
GSlider atmosphere; 
GLabel label5; 
GSlider population; 
